kind: Service
apiVersion: v1
metadata:
  name: dcbe-repo-nfs-service
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 32765
    - name: mountd2
      port: 32766
    - name: rpcbind
      port: 111
    - name: rpcbind2
      port: 32767
  selector:
    app: dcbe-repo-server
